### ISSUE TITLE
[FEAT] Linux support

### ISSUE THREAD

**Issue by leestarb** [Redume/EveryNasa#5]
Supporting that is very necessary for us!

**Comment by Redume** [comment]
Okay, I'm trying

**Comment by leestarb** [comment]
You shoudnt close the issue unless you are done with it!

**Comment by leestarb** [comment]
Also I would suggest you using libnofity as a toast library!

**Comment by Redume** [comment]
> Also I would suggest you using libnofity as a toast library!

Thanks, I'm trying it well. I'm trying to make a .deb package but it doesn't come out

**Comment by leestarb** [comment]
> > Also I would suggest you using libnofity as a toast library!
> 
> Thanks, I'm trying it well. I'm trying to make a .deb package but it doesn't come out

No need it that, just create a binary executable with pyinstaller and enjoy the show!

**Comment by Redume** [comment]
> No need it that, just create a binary executable with pyinstaller and enjoy the show!

Doesn't pyinstaller compile only .exe?

**Comment by leestarb** [comment]
> > No need it that, just create a binary executable with pyinstaller and enjoy the show!
> 
> Doesn't pyinstaller compile only .exe?

Excatly not. When running on linux, it easily creates a binary file (just like an exe)!

**Comment by Redume** [comment]
maybe I'm doing something wrong, but I dont have .deb

**Comment by Redume** [comment]
> maybe I'm doing something wrong, but I dont have .deb

And it also does not work through debuild on Debian

**Comment by leestarb** [comment]
> > maybe I'm doing something wrong, but I dont have .deb
> 
> And it also does not work through debuild on Debian

.deb is just an installable package. That contains your binary, you cant create it without binary, also ais no need in that, we just can run the binary.

**Comment by Redume** [comment]
> .deb is just an installable package. That contains your binary, you cant create it without binary, also ais no need in that, we just can run the binary.

Okay, I get it, I just don't find it convenient to use a computer with an open console, although this can be fixed by running the program in the background

**Comment by Redume** [comment]
Development is delayed because it is not possible to install wallpaper on the desktop, although I used to install it

**Comment by Redume** [comment]
I have two questions, is it possible to install wallpaper conditionally in Kde Plasma and is it possible to somehow install the application tray icon in Gnome?

**Comment by leestarb** [comment]
Of course

**Comment by Redume** [comment]
I made support for debian, and with GNOME, Kde plasma graphical shells, I will try to expand support in the future

**Comment by leestarb** [comment]
> I made support for debian, and with GNOME, Kde plasma graphical shells, I will try to expand support in the future

 Awesome stuff. But why is the readme for linux located in the src folder, which should contain source files only. I suggest making another folder to complain the readmes.

**Comment by Redume** [comment]
> I suggest making another folder to complain the readmes.

I don't quite understand what you're talking about

**Comment by Redume** [comment]
Do you mean to transfer `README.md` from [/src/linux](https://github.com/Redume/EveryNasa/tree/main/src/linux) to main `README.md`?

**Comment by leestarb** [comment]
Hey, I suggest making n AppImage package, which will be very convenient to use on any distro!

**Comment by Redume** [comment]
Now I want to try to make a Gui and rewrite everything in Golang
